# base_image:
#   image: bolabaseten/comfyui-truss-base:6a7bc35
  # python_executable_path: C:\Users\ashha\Documents\Development\_Work\YourPhysio\Trainings\100x GenAI Wizardry\03 Truss\truss-examples\.venv\Scripts\python.exe
description: Deploy a ComfyUI workflow as a Truss
build_commands:
- git clone https://github.com/comfyanonymous/ComfyUI.git
- cd ComfyUI && pip install -r requirements.txt
# - apt update && apt install wget
- cd ComfyUI/models/controlnet && wget -O diffusers_xl_canny_full.safetensors https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0/resolve/main/diffusion_pytorch_model.fp16.safetensors
- cd ComfyUI/models/checkpoints && wget -O sd_xl_base_1.0.safetensors https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input:
    workflow_values:
      positive_prompt: iphone apple with eyes of a lady, realistic
      negative_prompt: blurry, low quality
      steps: 30
      cfg: 7
model_name: ComfyUI Workflow
python_version: py39
requirements:
- websocket-client==1.6.4
- accelerate==0.23.0
- opencv-python
resources:
  accelerator: A10G
  cpu: '3'
  memory: 14Gi
  use_gpu: true
secrets: {}
system_packages:
- ffmpeg
- libgl1-mesa-glx
- wget
